package figuras;

import java.awt.Color;
import java.awt.Graphics;

public class PanelFiguras extends javax.swing.JPanel {

    /**
     * Creates new form PanelFiguras
     */
    private Circulos puntos;
    private Cuadrados cuadrados;
    private Triangulos triangulos;
    public PanelFiguras(Triangulos triangulos,Cuadrados cuadrados,Circulos puntos) {
        this.triangulos=triangulos;
        this.puntos = puntos;
        this.cuadrados = cuadrados;
        initComponents();
         setBackground(Color.lightGray);
        //this.add(figura, java.awt.BorderLayout.CENTER);
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        puntos.dibujar(g);
        cuadrados.dibujar(g);
        triangulos.dibujar(g);
    }
  

    public void addEventos(Controlador control){
       
        this.addMouseListener(control);
        this.addMouseMotionListener(control);
        
        this.addMouseWheelListener(control);
        
        this.cuadrado.addActionListener(control);
        this.circulo.addActionListener(control);
        this.triangulo.addActionListener(control);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelOeste = new javax.swing.JPanel();
        cuadrado = new javax.swing.JButton();
        triangulo = new javax.swing.JButton();
        circulo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        panelOeste.setBackground(new java.awt.Color(255, 255, 255));
        panelOeste.setBorder(javax.swing.BorderFactory.createLineBorder(getBackground(), 15));
        panelOeste.setLayout(new java.awt.GridLayout(5, 1, 15, 15));

        cuadrado.setText("Cuadrado");
        cuadrado.setName("cuadrado"); // NOI18N
        panelOeste.add(cuadrado);

        triangulo.setText("triangulo");
        triangulo.setName("triangulo"); // NOI18N
        panelOeste.add(triangulo);

        circulo.setText("circulo");
        circulo.setName("circulo"); // NOI18N
        panelOeste.add(circulo);

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelOeste.add(jButton1);

        add(panelOeste, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(1);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton circulo;
    private javax.swing.JButton cuadrado;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel panelOeste;
    private javax.swing.JButton triangulo;
    // End of variables declaration//GEN-END:variables



}
